name: "SmartPlaylist2PlaylistHarder"
guid: "5A63FE63-765F-43F7-A129-661E839F83D5"
imageUrl: ""
version: "2.3.0.1"
targetAbi: "10.11.0.0"
framework: "net9.0"
owner: "JMiles42"
overview: "Smart Playlist 2 Playlist Harder! Is a system to automatically generate playlists based on a set of rules\nBuilt off of the base of SmartPlaylist by ankenyr"
description: |
  Smart Playlist 2 Playlist Harder!.
  Is a system to automatically generate playlists based on a set of rules.
  Built off of the base of SmartPlaylist by ankenyr.
category: "Playlist"
artifacts:
  - "Jellyfin.Plugin.SmartPlaylist.dll"
changelog: |
  v2.3 Update to jellyfin 10.11.0
    Add SkipItems, the MaxItems existed allowing you to limit/Take a set number of items, you can now Skip, in a pagination style.

  v2.2 Added new functionality ExpressionVars, now along side the ExpressionSets there is a dictionary, of a string key and ExpressionValue value,
  This is used to share the same ExpressionValue across multiple Expressions, useful when repeating large lists etc.
  Please see the readme.md for more detail
  

  Fixed json parsing - Running unit tests after a major upgrade turns out to be a good idea.
  Updated to .net 8 and Jellyfin 10.9.0
  v2.* Changes have been made to the JSON schema, old files should still be read correctly, and when saved will use the new format.
  Added a Jobs page to the dashboard, to allow an admin to see the status of the playlist generation, it will include errors if they failed.
  Changed TargetValue, to be one or many values. You can either have it a  single json value like a string, number or bool. Or an array of values. This allows a single Expression to match multiple values, rather then needing many single Expressions.
  Added a MatchMode option, to allow selection of how sets of values are considered to be valid.
    Modes are, Any, All, OnlyOne, AllButOne, None, Half, HalfOrMore, HalfOrLess.
    Defualts 
     SmartPlaylist is Any, meaning as long as one ExpressionSet matches the item is included.
     ExpressionSet is All, meaning all Expressions must match for the item to be included.
     Expression is Any, meaning only one of the TargetValues must match for the item to be included.
  Added config options to the Plugin config page.
    Options include
      PlaylistBatchedProcessing - Batch playlists by user and ItemKinds, allows processing of multiple playlits at once (may have performace impacts)
      PlaylistDetailedErrors - Show the whole StackTrace of an error on the jobs details page.
      AlwaysSaveFile - Always save the json file, when processing the playlist.
      BackupFileOnSave - Backup files on save
      PlaylistFolderName - Allow you to specify the folder within the Jellyfin Data folder to store playlists
      PlaylistBackupFolderName - Allow you to specify the folder within the Jellyfin Data folder to store backups playlists
      PlaylistSorterThreadCount - Set the thread count for how many Items are processed in parallel
      