// Global using directives

global using Jellyfin.Data.Entities;
global using Jellyfin.Data.Enums;
global using Jellyfin.Plugin.SmartPlaylist.Configuration;
global using Jellyfin.Plugin.SmartPlaylist.Extensions;
global using Jellyfin.Plugin.SmartPlaylist.Infrastructure.ProcessEngine;
global using Jellyfin.Plugin.SmartPlaylist.Infrastructure.QueryEngine.Compiler;
global using Jellyfin.Plugin.SmartPlaylist.Infrastructure.QueryEngine.Containers;
global using Jellyfin.Plugin.SmartPlaylist.Infrastructure.QueryEngine.Model;
global using Jellyfin.Plugin.SmartPlaylist.Infrastructure.QueryEngine.Operators;
global using Jellyfin.Plugin.SmartPlaylist.Infrastructure.QueryEngine.Ordering;
global using Jellyfin.Plugin.SmartPlaylist.Infrastructure.QueryEngine.RuleFixers;
global using Jellyfin.Plugin.SmartPlaylist.Infrastructure.QueryEngine;
global using Jellyfin.Plugin.SmartPlaylist.Infrastructure.Serializer;
global using Jellyfin.Plugin.SmartPlaylist.Infrastructure;
global using Jellyfin.Plugin.SmartPlaylist.Models.Dto;
global using Jellyfin.Plugin.SmartPlaylist.Models.ExpressionValues;
global using Jellyfin.Plugin.SmartPlaylist.Models;
global using MediaBrowser.Common.Configuration;
global using MediaBrowser.Common.Plugins;
global using MediaBrowser.Controller.Entities.Movies;
global using MediaBrowser.Controller.Entities.TV;
global using MediaBrowser.Controller.Entities;
global using MediaBrowser.Controller.Library;
global using MediaBrowser.Model.Plugins;
global using MediaBrowser.Model.Serialization;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using System.Collections.Concurrent;
global using System.Collections.Generic;
global using System.Collections;
global using System.Globalization;
global using System.IO;
global using System.Linq;
global using System.Reflection;
global using System.Runtime.Serialization;
global using System.Text.Json.Serialization;
global using System.Text.Json;
global using System.Text.RegularExpressions;
global using System.Text;
global using System.Threading.Tasks;
global using System.Threading;
global using System;
global using LinqExpression = System.Linq.Expressions.Expression;
global using ParameterExpression = System.Linq.Expressions.ParameterExpression;
global using MemberExpression = System.Linq.Expressions.MemberExpression;
global using UnaryExpression = System.Linq.Expressions.UnaryExpression;
global using ConstantExpression = System.Linq.Expressions.ConstantExpression;
global using LinqExpressionType = System.Linq.Expressions.ExpressionType;
