namespace Jellyfin.Plugin.SmartPlaylist.QueryEngine;

public static class OperandMemberEnumExtensions
{
	public static string ToStringFast(this OperandMember states) {
		return states switch {
				OperandMember.Name => nameof(OperandMember.Name),
				OperandMember.Actors => nameof(OperandMember.Actors),
				OperandMember.Artists => nameof(OperandMember.Artists),
				OperandMember.AllText => nameof(OperandMember.AllText),
				OperandMember.Composers => nameof(OperandMember.Composers),
				OperandMember.Directors => nameof(OperandMember.Directors),
				OperandMember.Genres => nameof(OperandMember.Genres),
				OperandMember.GuestStars => nameof(OperandMember.GuestStars),
				OperandMember.Producers => nameof(OperandMember.Producers),
				OperandMember.Studios => nameof(OperandMember.Studios),
				OperandMember.Writers => nameof(OperandMember.Writers),
				OperandMember.Exists => nameof(OperandMember.Exists),
				OperandMember.HasSubtitles => nameof(OperandMember.HasSubtitles),
				OperandMember.IsFavoriteOrLiked => nameof(OperandMember.IsFavoriteOrLiked),
				OperandMember.IsHorizontal => nameof(OperandMember.IsHorizontal),
				OperandMember.IsPlayed => nameof(OperandMember.IsPlayed),
				OperandMember.IsSquare => nameof(OperandMember.IsSquare),
				OperandMember.IsVertical => nameof(OperandMember.IsVertical),
				OperandMember.DateCreated => nameof(OperandMember.DateCreated),
				OperandMember.DateLastRefreshed => nameof(OperandMember.DateLastRefreshed),
				OperandMember.DateLastSaved => nameof(OperandMember.DateLastSaved),
				OperandMember.DateModified => nameof(OperandMember.DateModified),
				OperandMember.PlayedPercentage => nameof(OperandMember.PlayedPercentage),
				OperandMember.PremiereDate => nameof(OperandMember.PremiereDate),
				OperandMember.LastPlayedDate => nameof(OperandMember.LastPlayedDate),
				OperandMember.CommunityRating => nameof(OperandMember.CommunityRating),
				OperandMember.CriticRating => nameof(OperandMember.CriticRating),
				OperandMember.DaysSinceCreated => nameof(OperandMember.DaysSinceCreated),
				OperandMember.DaysSinceLastModified => nameof(OperandMember.DaysSinceLastModified),
				OperandMember.DaysSinceLastRefreshed => nameof(OperandMember.DaysSinceLastRefreshed),
				OperandMember.DaysSinceLastSaved => nameof(OperandMember.DaysSinceLastSaved),
				OperandMember.DaysSincePremiereDate => nameof(OperandMember.DaysSincePremiereDate),
				OperandMember.Height => nameof(OperandMember.Height),
				OperandMember.PlayedCount => nameof(OperandMember.PlayedCount),
				OperandMember.Width => nameof(OperandMember.Width),
				OperandMember.AiredSeasonNumber => nameof(OperandMember.AiredSeasonNumber),
				OperandMember.ParentIndexNumber => nameof(OperandMember.ParentIndexNumber),
				OperandMember.ProductionYear => nameof(OperandMember.ProductionYear),
				OperandMember.PlaybackPositionTicks => nameof(OperandMember.PlaybackPositionTicks),
				OperandMember.Album => nameof(OperandMember.Album),
				OperandMember.CollectionName => nameof(OperandMember.CollectionName),
				OperandMember.Container => nameof(OperandMember.Container),
				OperandMember.FileNameWithoutExtension => nameof(OperandMember.FileNameWithoutExtension),
				OperandMember.FolderPath => nameof(OperandMember.FolderPath),
				OperandMember.GrandparentName => nameof(OperandMember.GrandparentName),
				OperandMember.MediaType => nameof(OperandMember.MediaType),
				OperandMember.OfficialRating => nameof(OperandMember.OfficialRating),
				OperandMember.OriginalTitle => nameof(OperandMember.OriginalTitle),
				OperandMember.Overview => nameof(OperandMember.Overview),
				OperandMember.ParentName => nameof(OperandMember.ParentName),
				OperandMember.SeasonName => nameof(OperandMember.SeasonName),
				OperandMember.SeriesName => nameof(OperandMember.SeriesName),
				OperandMember.SortName => nameof(OperandMember.SortName),
				OperandMember.Length => nameof(OperandMember.Length),
				OperandMember.LengthSeconds => nameof(OperandMember.LengthSeconds),
				OperandMember.LengthMinutes => nameof(OperandMember.LengthMinutes),
				OperandMember.LengthHours => nameof(OperandMember.LengthHours),
				OperandMember.LengthTicks => nameof(OperandMember.LengthTicks),
				OperandMember.Tags => nameof(OperandMember.Tags),
				_ => throw new ArgumentOutOfRangeException(nameof(states), states, null)
		};
	}

	public static bool IsDefinedFast(OperandMember states) {
		return states switch {
				OperandMember.Name => true,
				OperandMember.Actors => true,
				OperandMember.Artists => true,
				OperandMember.AllText => true,
				OperandMember.Composers => true,
				OperandMember.Directors => true,
				OperandMember.Genres => true,
				OperandMember.GuestStars => true,
				OperandMember.Producers => true,
				OperandMember.Studios => true,
				OperandMember.Writers => true,
				OperandMember.Exists => true,
				OperandMember.HasSubtitles => true,
				OperandMember.IsFavoriteOrLiked => true,
				OperandMember.IsHorizontal => true,
				OperandMember.IsPlayed => true,
				OperandMember.IsSquare => true,
				OperandMember.IsVertical => true,
				OperandMember.DateCreated => true,
				OperandMember.DateLastRefreshed => true,
				OperandMember.DateLastSaved => true,
				OperandMember.DateModified => true,
				OperandMember.PlayedPercentage => true,
				OperandMember.PremiereDate => true,
				OperandMember.LastPlayedDate => true,
				OperandMember.CommunityRating => true,
				OperandMember.CriticRating => true,
				OperandMember.DaysSinceCreated => true,
				OperandMember.DaysSinceLastModified => true,
				OperandMember.DaysSinceLastRefreshed => true,
				OperandMember.DaysSinceLastSaved => true,
				OperandMember.DaysSincePremiereDate => true,
				OperandMember.Height => true,
				OperandMember.PlayedCount => true,
				OperandMember.Width => true,
				OperandMember.AiredSeasonNumber => true,
				OperandMember.ParentIndexNumber => true,
				OperandMember.ProductionYear => true,
				OperandMember.PlaybackPositionTicks => true,
				OperandMember.Album => true,
				OperandMember.CollectionName => true,
				OperandMember.Container => true,
				OperandMember.FileNameWithoutExtension => true,
				OperandMember.FolderPath => true,
				OperandMember.GrandparentName => true,
				OperandMember.MediaType => true,
				OperandMember.OfficialRating => true,
				OperandMember.OriginalTitle => true,
				OperandMember.Overview => true,
				OperandMember.ParentName => true,
				OperandMember.SeasonName => true,
				OperandMember.SeriesName => true,
				OperandMember.SortName => true,
				OperandMember.Length => true,
				OperandMember.LengthSeconds => true,
				OperandMember.LengthMinutes => true,
				OperandMember.LengthHours => true,
				OperandMember.LengthTicks => true,
				OperandMember.Tags => true,
				_ => false
		};
	}

	public static bool IsDefinedFast(string states) {
		return states switch {
			nameof(OperandMember.Name) => true,
			nameof(OperandMember.Actors) => true,
			nameof(OperandMember.Artists) => true,
			nameof(OperandMember.AllText) => true,
			nameof(OperandMember.Composers) => true,
			nameof(OperandMember.Directors) => true,
			nameof(OperandMember.Genres) => true,
			nameof(OperandMember.GuestStars) => true,
			nameof(OperandMember.Producers) => true,
			nameof(OperandMember.Studios) => true,
			nameof(OperandMember.Writers) => true,
			nameof(OperandMember.Exists) => true,
			nameof(OperandMember.HasSubtitles) => true,
			nameof(OperandMember.IsFavoriteOrLiked) => true,
			nameof(OperandMember.IsHorizontal) => true,
			nameof(OperandMember.IsPlayed) => true,
			nameof(OperandMember.IsSquare) => true,
			nameof(OperandMember.IsVertical) => true,
			nameof(OperandMember.DateCreated) => true,
			nameof(OperandMember.DateLastRefreshed) => true,
			nameof(OperandMember.DateLastSaved) => true,
			nameof(OperandMember.DateModified) => true,
			nameof(OperandMember.PlayedPercentage) => true,
			nameof(OperandMember.PremiereDate) => true,
			nameof(OperandMember.LastPlayedDate) => true,
			nameof(OperandMember.CommunityRating) => true,
			nameof(OperandMember.CriticRating) => true,
			nameof(OperandMember.DaysSinceCreated) => true,
			nameof(OperandMember.DaysSinceLastModified) => true,
			nameof(OperandMember.DaysSinceLastRefreshed) => true,
			nameof(OperandMember.DaysSinceLastSaved) => true,
			nameof(OperandMember.DaysSincePremiereDate) => true,
			nameof(OperandMember.Height) => true,
			nameof(OperandMember.PlayedCount) => true,
			nameof(OperandMember.Width) => true,
			nameof(OperandMember.AiredSeasonNumber) => true,
			nameof(OperandMember.ParentIndexNumber) => true,
			nameof(OperandMember.ProductionYear) => true,
			nameof(OperandMember.PlaybackPositionTicks) => true,
			nameof(OperandMember.Album) => true,
			nameof(OperandMember.CollectionName) => true,
			nameof(OperandMember.Container) => true,
			nameof(OperandMember.FileNameWithoutExtension) => true,
			nameof(OperandMember.FolderPath) => true,
			nameof(OperandMember.GrandparentName) => true,
			nameof(OperandMember.MediaType) => true,
			nameof(OperandMember.OfficialRating) => true,
			nameof(OperandMember.OriginalTitle) => true,
			nameof(OperandMember.Overview) => true,
			nameof(OperandMember.ParentName) => true,
			nameof(OperandMember.SeasonName) => true,
			nameof(OperandMember.SeriesName) => true,
			nameof(OperandMember.SortName) => true,
			nameof(OperandMember.Length) => true,
			nameof(OperandMember.LengthSeconds) => true,
			nameof(OperandMember.LengthMinutes) => true,
			nameof(OperandMember.LengthHours) => true,
			nameof(OperandMember.LengthTicks) => true,
			nameof(OperandMember.Tags) => true,
			_ => false
		};
	}

	public static OperandMember? GetFast(string states) {
		return states switch {
			nameof(OperandMember.Name) => OperandMember.Name,
			nameof(OperandMember.Actors) => OperandMember.Actors,
			nameof(OperandMember.Artists) => OperandMember.Artists,
			nameof(OperandMember.AllText) => OperandMember.AllText,
			nameof(OperandMember.Composers) => OperandMember.Composers,
			nameof(OperandMember.Directors) => OperandMember.Directors,
			nameof(OperandMember.Genres) => OperandMember.Genres,
			nameof(OperandMember.GuestStars) => OperandMember.GuestStars,
			nameof(OperandMember.Producers) => OperandMember.Producers,
			nameof(OperandMember.Studios) => OperandMember.Studios,
			nameof(OperandMember.Writers) => OperandMember.Writers,
			nameof(OperandMember.Exists) => OperandMember.Exists,
			nameof(OperandMember.HasSubtitles) => OperandMember.HasSubtitles,
			nameof(OperandMember.IsFavoriteOrLiked) => OperandMember.IsFavoriteOrLiked,
			nameof(OperandMember.IsHorizontal) => OperandMember.IsHorizontal,
			nameof(OperandMember.IsPlayed) => OperandMember.IsPlayed,
			nameof(OperandMember.IsSquare) => OperandMember.IsSquare,
			nameof(OperandMember.IsVertical) => OperandMember.IsVertical,
			nameof(OperandMember.DateCreated) => OperandMember.DateCreated,
			nameof(OperandMember.DateLastRefreshed) => OperandMember.DateLastRefreshed,
			nameof(OperandMember.DateLastSaved) => OperandMember.DateLastSaved,
			nameof(OperandMember.DateModified) => OperandMember.DateModified,
			nameof(OperandMember.PlayedPercentage) => OperandMember.PlayedPercentage,
			nameof(OperandMember.PremiereDate) => OperandMember.PremiereDate,
			nameof(OperandMember.LastPlayedDate) => OperandMember.LastPlayedDate,
			nameof(OperandMember.CommunityRating) => OperandMember.CommunityRating,
			nameof(OperandMember.CriticRating) => OperandMember.CriticRating,
			nameof(OperandMember.DaysSinceCreated) => OperandMember.DaysSinceCreated,
			nameof(OperandMember.DaysSinceLastModified) => OperandMember.DaysSinceLastModified,
			nameof(OperandMember.DaysSinceLastRefreshed) => OperandMember.DaysSinceLastRefreshed,
			nameof(OperandMember.DaysSinceLastSaved) => OperandMember.DaysSinceLastSaved,
			nameof(OperandMember.DaysSincePremiereDate) => OperandMember.DaysSincePremiereDate,
			nameof(OperandMember.Height) => OperandMember.Height,
			nameof(OperandMember.PlayedCount) => OperandMember.PlayedCount,
			nameof(OperandMember.Width) => OperandMember.Width,
			nameof(OperandMember.AiredSeasonNumber) => OperandMember.AiredSeasonNumber,
			nameof(OperandMember.ParentIndexNumber) => OperandMember.ParentIndexNumber,
			nameof(OperandMember.ProductionYear) => OperandMember.ProductionYear,
			nameof(OperandMember.PlaybackPositionTicks) => OperandMember.PlaybackPositionTicks,
			nameof(OperandMember.Album) => OperandMember.Album,
			nameof(OperandMember.CollectionName) => OperandMember.CollectionName,
			nameof(OperandMember.Container) => OperandMember.Container,
			nameof(OperandMember.FileNameWithoutExtension) => OperandMember.FileNameWithoutExtension,
			nameof(OperandMember.FolderPath) => OperandMember.FolderPath,
			nameof(OperandMember.GrandparentName) => OperandMember.GrandparentName,
			nameof(OperandMember.MediaType) => OperandMember.MediaType,
			nameof(OperandMember.OfficialRating) => OperandMember.OfficialRating,
			nameof(OperandMember.OriginalTitle) => OperandMember.OriginalTitle,
			nameof(OperandMember.Overview) => OperandMember.Overview,
			nameof(OperandMember.ParentName) => OperandMember.ParentName,
			nameof(OperandMember.SeasonName) => OperandMember.SeasonName,
			nameof(OperandMember.SeriesName) => OperandMember.SeriesName,
			nameof(OperandMember.SortName) => OperandMember.SortName,
			nameof(OperandMember.Length) => OperandMember.Length,
			nameof(OperandMember.LengthSeconds) => OperandMember.LengthSeconds,
			nameof (OperandMember.LengthMinutes) => OperandMember.LengthMinutes,
			nameof(OperandMember.LengthHours) => OperandMember.LengthHours,
			nameof(OperandMember.LengthTicks) => OperandMember.LengthTicks,
			nameof(OperandMember.Tags) => OperandMember.Tags,
			_ => null
		};
	}

	public static string ToDisplayFast(this OperandMember states) {
		return states switch {
				OperandMember.Name => "Name",
				OperandMember.Actors => "Actors",
				OperandMember.Artists => "Artists",
				OperandMember.AllText => "AllText",
				OperandMember.Composers => "Composers",
				OperandMember.Directors => "Directors",
				OperandMember.Genres => "Genres",
				OperandMember.GuestStars => "GuestStars",
				OperandMember.Producers => "Producers",
				OperandMember.Studios => "Studios",
				OperandMember.Writers => "Writers",
				OperandMember.Exists => "Exists",
				OperandMember.HasSubtitles => "HasSubtitles",
				OperandMember.IsFavoriteOrLiked => "IsFavoriteOrLiked",
				OperandMember.IsHorizontal => "IsHorizontal",
				OperandMember.IsPlayed => "IsPlayed",
				OperandMember.IsSquare => "IsSquare",
				OperandMember.IsVertical => "IsVertical",
				OperandMember.DateCreated => "DateCreated",
				OperandMember.DateLastRefreshed => "DateLastRefreshed",
				OperandMember.DateLastSaved => "DateLastSaved",
				OperandMember.DateModified => "DateModified",
				OperandMember.PlayedPercentage => "PlayedPercentage",
				OperandMember.PremiereDate => "PremiereDate",
				OperandMember.LastPlayedDate => "LastPlayedDate",
				OperandMember.CommunityRating => "CommunityRating",
				OperandMember.CriticRating => "CriticRating",
				OperandMember.DaysSinceCreated => "DaysSinceCreated",
				OperandMember.DaysSinceLastModified => "DaysSinceLastModified",
				OperandMember.DaysSinceLastRefreshed => "DaysSinceLastRefreshed",
				OperandMember.DaysSinceLastSaved => "DaysSinceLastSaved",
				OperandMember.DaysSincePremiereDate => "DaysSincePremiereDate",
				OperandMember.Height => "Height",
				OperandMember.PlayedCount => "PlayedCount",
				OperandMember.Width => "Width",
				OperandMember.AiredSeasonNumber => "AiredSeasonNumber",
				OperandMember.ParentIndexNumber => "ParentIndexNumber",
				OperandMember.ProductionYear => "ProductionYear",
				OperandMember.PlaybackPositionTicks => "PlaybackPositionTicks",
				OperandMember.Album => "Album",
				OperandMember.CollectionName => "CollectionName",
				OperandMember.Container => "Container",
				OperandMember.FileNameWithoutExtension => "FileNameWithoutExtension",
				OperandMember.FolderPath => "FolderPath",
				OperandMember.GrandparentName => "GrandparentName",
				OperandMember.MediaType => "MediaType",
				OperandMember.OfficialRating => "OfficialRating",
				OperandMember.OriginalTitle => "OriginalTitle",
				OperandMember.Overview => "Overview",
				OperandMember.ParentName => "ParentName",
				OperandMember.SeasonName => "SeasonName",
				OperandMember.SeriesName => "SeriesName",
				OperandMember.SortName => "SortName",
				OperandMember.Length => "Length",
				OperandMember.LengthSeconds => "LengthSeconds",
				OperandMember.LengthMinutes => "LengthMinutes",
				OperandMember.LengthHours => "LengthHours",
				OperandMember.LengthTicks => "LengthTicks",
				OperandMember.Tags => "Tags",
				_ => throw new ArgumentOutOfRangeException(nameof(states), states, null)
		};
	}

	public static OperandMember[] GetValuesFast() {
		return new[] {
				OperandMember.Name,
				OperandMember.Actors,
				OperandMember.Artists,
				OperandMember.AllText,
				OperandMember.Composers,
				OperandMember.Directors,
				OperandMember.Genres,
				OperandMember.GuestStars,
				OperandMember.Producers,
				OperandMember.Studios,
				OperandMember.Writers,
				OperandMember.Exists,
				OperandMember.HasSubtitles,
				OperandMember.IsFavoriteOrLiked,
				OperandMember.IsHorizontal,
				OperandMember.IsPlayed,
				OperandMember.IsSquare,
				OperandMember.IsVertical,
				OperandMember.DateCreated,
				OperandMember.DateLastRefreshed,
				OperandMember.DateLastSaved,
				OperandMember.DateModified,
				OperandMember.PlayedPercentage,
				OperandMember.PremiereDate,
				OperandMember.LastPlayedDate,
				OperandMember.CommunityRating,
				OperandMember.CriticRating,
				OperandMember.DaysSinceCreated,
				OperandMember.DaysSinceLastModified,
				OperandMember.DaysSinceLastRefreshed,
				OperandMember.DaysSinceLastSaved,
				OperandMember.DaysSincePremiereDate,
				OperandMember.Height,
				OperandMember.PlayedCount,
				OperandMember.Width,
				OperandMember.AiredSeasonNumber,
				OperandMember.ParentIndexNumber,
				OperandMember.ProductionYear,
				OperandMember.PlaybackPositionTicks,
				OperandMember.Album,
				OperandMember.CollectionName,
				OperandMember.Container,
				OperandMember.FileNameWithoutExtension,
				OperandMember.FolderPath,
				OperandMember.GrandparentName,
				OperandMember.MediaType,
				OperandMember.OfficialRating,
				OperandMember.OriginalTitle,
				OperandMember.Overview,
				OperandMember.ParentName,
				OperandMember.SeasonName,
				OperandMember.SeriesName,
				OperandMember.SortName,
				OperandMember.Length,
				OperandMember.LengthSeconds,
				OperandMember.LengthMinutes,
				OperandMember.LengthHours,
				OperandMember.LengthTicks,
				OperandMember.Tags,
		};
	}

	public static string[] GetNamesFast() {
		return new[] {
				nameof(OperandMember.Name),
				nameof(OperandMember.Actors),
				nameof(OperandMember.Artists),
				nameof(OperandMember.AllText),
				nameof(OperandMember.Composers),
				nameof(OperandMember.Directors),
				nameof(OperandMember.Genres),
				nameof(OperandMember.GuestStars),
				nameof(OperandMember.Producers),
				nameof(OperandMember.Studios),
				nameof(OperandMember.Writers),
				nameof(OperandMember.Exists),
				nameof(OperandMember.HasSubtitles),
				nameof(OperandMember.IsFavoriteOrLiked),
				nameof(OperandMember.IsHorizontal),
				nameof(OperandMember.IsPlayed),
				nameof(OperandMember.IsSquare),
				nameof(OperandMember.IsVertical),
				nameof(OperandMember.DateCreated),
				nameof(OperandMember.DateLastRefreshed),
				nameof(OperandMember.DateLastSaved),
				nameof(OperandMember.DateModified),
				nameof(OperandMember.PlayedPercentage),
				nameof(OperandMember.PremiereDate),
				nameof(OperandMember.LastPlayedDate),
				nameof(OperandMember.CommunityRating),
				nameof(OperandMember.CriticRating),
				nameof(OperandMember.DaysSinceCreated),
				nameof(OperandMember.DaysSinceLastModified),
				nameof(OperandMember.DaysSinceLastRefreshed),
				nameof(OperandMember.DaysSinceLastSaved),
				nameof(OperandMember.DaysSincePremiereDate),
				nameof(OperandMember.Height),
				nameof(OperandMember.PlayedCount),
				nameof(OperandMember.Width),
				nameof(OperandMember.AiredSeasonNumber),
				nameof(OperandMember.ParentIndexNumber),
				nameof(OperandMember.ProductionYear),
				nameof(OperandMember.PlaybackPositionTicks),
				nameof(OperandMember.Album),
				nameof(OperandMember.CollectionName),
				nameof(OperandMember.Container),
				nameof(OperandMember.FileNameWithoutExtension),
				nameof(OperandMember.FolderPath),
				nameof(OperandMember.GrandparentName),
				nameof(OperandMember.MediaType),
				nameof(OperandMember.OfficialRating),
				nameof(OperandMember.OriginalTitle),
				nameof(OperandMember.Overview),
				nameof(OperandMember.ParentName),
				nameof(OperandMember.SeasonName),
				nameof(OperandMember.SeriesName),
				nameof(OperandMember.SortName),
				nameof(OperandMember.Length),
				nameof(OperandMember.LengthSeconds),
				nameof(OperandMember.LengthMinutes),
				nameof(OperandMember.LengthHours),
				nameof(OperandMember.LengthTicks),
				nameof(OperandMember.Tags),
		};
	}

	public static int GetLengthFast() => 59;
}